### ISSUE TITLE
Segmentation fault during assigning reads to LCA

### ISSUE THREAD

**Issue by sturne29** [seqan/slimm#24] opened 2018-05-23 17:54 UTC
Might be an issue with my setup, but I thought I'd ask anyway. As far as I know, I've done everything correctly in set up (downloaded binary for my system, got the bowtie2 index and the database, used bowtie2 and samtools to generate the .bam file). I get a segmentation fault during the "assigning reads to LCA" step when I try to run slimm with the .bam file. 

For reference, I'm trying to use the program in a shared cluster environment (my local workstation is lacking in memory). 

Any ideas? Thanks in advance!

**Comment by temehi** [comment] 2018-06-01 21:03
Hello,

Thanks for using slimm. 

Is it possible for you to share your bam file, so that I can investigate the issue?

**Comment by sturne29** [comment] 2018-06-06 19:08
Here is a link to a Google drive with the file:
https://drive.google.com/open?id=1HQ_1TXXivQsOQkxRCutAzxHI5wVzHwN3

**Comment by temehi** [comment] 2018-06-10 22:35
Thanks for sharing the file. Just right now, I was able to reproduce your issue. I will look into it and get back to you with a fix soon.

**Comment by temehi** [comment] 2018-06-11 00:28
The issue seems to be with the incomplete SLIMM database at http://ftp.mi.fu-berlin.de/pub/dadi/slimm/slimm_db_13K.sldb

I have rebuilt and uploaded a new database at the same place. You can retry to run SLIMM with the new database. 

In any case, the case should be handled more gracefully than just a segmentation fault.

**Comment by sturne29** [comment] 2018-06-12 17:23
Thank you! I'll give that a try!

**Comment by temehi** [comment] 2018-06-15 14:27
@sturne29 Did the new database fixed your issue? 
I have fixed the issue in a new release ([Release 0.3.2 (https://github.com/seqan/slimm/releases/latest)). Now a segmentation fault will not happen even if the taxonomic database is missing some of the references. In any case, I recommend using the updated database which is complete.

I am closing the issue now.

**Comment by fconstancias** [comment] 2018-11-15 10:24
Hello,

I am experiencing a similar issue.
I am running slimm0.3.2 on 24 bam files generated with metagenomes using bowtie2.2.9 against the AB_13K database and using the following commands :

```
slimm  -w 400 \
	   --directory \
	   -o ${OUT2}/  \
	  /bank/kraken/SLIMM/slimm_db_13K.sldb  \
	  -ro \
	  --min-reads 0 \
	  --cov-cut-off 0.95 \
	  --abundance-cut-off 0 \
	  --raw-output \
	  -v \
	  ${OUT}

```
slimm is able to process a few samples and then crashes.

```
Reading 12 of 24 files ... (MBD016LE.bam)
Intializing coverages for all reference genome ... [1 secs]
Analysing alignments, reads and references ....... [1 secs]
  635796 records processed.
    156065 matching reads
    95372 uniquily matching reads
  references with reads = 1386
  expected bins coverage = 0.0122491
  bins coverage cut-off = 0.0146931 (0.95 quantile)
  uniq bins coverage cut-off = 0.000189179 (0.95 quantile)

Filtering unlikely sequences ..................... [0 secs]
  11 passed the threshould coverage.
  1330 ref's couldn't pass the coverage threshould.
  1337 ref's couldn't pass the uniq coverage threshould.
  uniquily matching reads increased from 95372 to 6421

Writing features to a file ....................... [0 secs]
Assigning reads to Least Common Ancestor (LCA) ... [0 secs]
Writing taxnomic profile(s) ...................... /storage/mi/dadi/workspace/development/slimm/include/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::out_of_range: _Map_base::at)

stack trace:
  0                      [0x449c19]
  1                      [0x44a1c6]
  2                      [0x47e326]
  3                      [0x47e371]
  4                      [0x471c73]
  5                      [0x4d0e1f]
  6                      [0x41d41c]
  7                      [0x4459b8]
  8                      [0x4230a0]
  9                      [0x404cbf]
 10                      [0x514740]
 11                      [0x4060a7]

/var/spool/sge/cc2-bigmem2/job_scripts/6727495: line 35: 64284 Aborted                 (core dumped) slimm -w 400 --directory -o ${OUT2}/ /bank/kraken/SLIMM/slimm_db_13K.sldb -ro --min-reads 0 --cov-cut-off 0.95 --abundance-cut-off 0 --raw-output -v ${OUT}

```

Interestingly, when keeping -w to 0 (default), slimm crashes processing the first sample in the --directory :
```
slimm  -w 0 \
	   --directory \
	   -o ${OUT2}/  \
	  /bank/kraken/SLIMM/slimm_db_13K.sldb  \
	  -ro \
	  --min-reads 0 \
	  --cov-cut-off 0.95 \
	  --abundance-cut-off 0 \
	  --raw-output \
	  -v \
	  ${OUT}
```

```
Reading 1 of 24 files ... (MBC023LE.bam)
=================================================================
Intializing coverages for all reference genome ... [2 secs]
Analysing alignments, reads and references ....... [2 secs]
  1428768 records processed.
    233973 matching reads
    110310 uniquily matching reads
  references with reads = 2916
  expected bins coverage = 0.0702342
  bins coverage cut-off = 0.0129297 (0.95 quantile)
  uniq bins coverage cut-off = 0.000147351 (0.95 quantile)

Filtering unlikely sequences ..................... [0 secs]
  19 passed the threshould coverage.
  2850 ref's couldn't pass the coverage threshould.
  2772 ref's couldn't pass the uniq coverage threshould.
  uniquily matching reads increased from 110310 to 21041

Writing features to a file ....................... [1 secs]
Assigning reads to Least Common Ancestor (LCA) ... [0 secs]
Writing taxnomic profile(s) ...................... /storage/mi/dadi/workspace/development/slimm/include/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::out_of_range: _Map_base::at)

stack trace:
  0                      [0x449c19]
  1                      [0x44a1c6]
  2                      [0x47e326]
  3                      [0x47e371]
  4                      [0x471c73]
  5                      [0x4d0e1f]
  6                      [0x41d41c]
  7                      [0x4459b8]
  8                      [0x4230a0]
  9                      [0x404cbf]
 10                      [0x514740]
 11                      [0x4060a7]

/var/spool/sge/cc2-bigmem2/job_scripts/6727495: line 65: 65108 Aborted                 (core dumped) slimm -w 0 --directory -o ${OUT2}/ /bank/kraken/SLIMM/slimm_db_13K.sldb -ro --min-reads 0 --cov-cut-off 0.95 --abundance-cut-off 0 --raw-output -v ${OUT}
### JOB END ###

```

I am running these commands on a cluster using the following parameters : 
```
#$ -pe parallel_smp 10
#$ -l mem_free=10G
```

If you have any thoughts on what is happening here.

Cheers

**Comment by temehi** [comment] 2018-11-15 21:45
Hi,

I was able to reproduce the problem. I have narrowed it to using the `--directory` option. I am guessing some data is being accumulated over the files. The profiles are also wrong exept for the first file.  As a temporary solution, you can run SLIMM on individual files one by one using a for loop or something. 
```
for BAM_FILE in ${OUT}/*; do  
     slimm  -w 0 \
	   -o ${OUT2}/  \
	  /bank/kraken/SLIMM/slimm_db_13K.sldb  \
	  -ro \
	  --min-reads 0 \
	  --cov-cut-off 0.95 \
	  --abundance-cut-off 0 \
	  --raw-output \
	  -v \
	  ${BAM_FILE}
done
```
I will close this old issue as I have oppend a new issue (#33). I will get back to you as soon as I fix this issue. 

Best,
THD

**Closed as completed by temehi** 2018-11-15 21:45 UTC
